name: Build_GitHubPages

on:
  push:
    branches:
      - main

jobs:
  ladle_deploy:
    name: Build ladle and deploy gh-pages
    runs-on: ubuntu-latest
    container:
      image: node:lts-slim
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build ladle
        run: |
          npm ci
          npm run ladle:build
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CNAME: vite-react-ladle.dev.be-geek.net
